/**
 * NestJS injection tokens for notification-platform interfaces.
 * Interfaces can't be injected by type — every interface-typed dependency
 * goes through an explicit string token (standard NestJS DI pattern).
 */
export const OUTBOX_STORE = 'NOTIFICATIONS_OUTBOX_STORE';
export const DEDUP_STORE = 'NOTIFICATIONS_DEDUP_STORE';
export const RECIPIENT_DIRECTORY = 'NOTIFICATIONS_RECIPIENT_DIRECTORY';
export const PREFERENCES_STORE = 'NOTIFICATIONS_PREFERENCES_STORE';
export const DEAD_LETTER_SINK = 'NOTIFICATIONS_DEAD_LETTER_SINK';
export const DIGEST_QUEUE = 'NOTIFICATIONS_DIGEST_QUEUE';
export const DIGEST_QUEUE_READER = 'NOTIFICATIONS_DIGEST_QUEUE_READER';
export const METRICS_RECORDER = 'NOTIFICATIONS_METRICS_RECORDER';
export const REALTIME_TRANSPORT = 'NOTIFICATIONS_REALTIME_TRANSPORT';
export const TEMPLATE_ENGINE = 'NOTIFICATIONS_TEMPLATE_ENGINE';
export const NOTIFICATION_CHANNELS = 'NOTIFICATIONS_CHANNELS_MAP';
export const OUTBOX_DISPATCHER = 'NOTIFICATIONS_OUTBOX_DISPATCHER';
